<?php

declare(strict_types=1);

namespace Swag\AssistantStarterKit\Migration;

use Doctrine\DBAL\Connection;
use Shopware\Core\Framework\Migration\MigrationStep;

/**
 * Creates `swag_assistant_conversation` and `swag_assistant_trace_event`.
 *
 * Written by hand rather than generated by a custom entity: `entities.xml` is registered only by
 * `AppManager`, so custom entities are an **App** feature and D1 chose a plugin (ruling R78).
 *
 * Two schema decisions are load-bearing rather than habitual:
 *
 * - **`ON DELETE CASCADE` on the foreign key.** A retention task will prune conversations, and a
 *   pruned conversation must take its trace events with it. `ARCHITECTURE.md` calls the retention
 *   task "not optional" because these rows live in the merchant's database; orphaned events would
 *   make it a task that only appears to work.
 * - **An index on `(conversation_id, seq)`.** Reading a trace means reading one conversation's events
 *   in order, which is the only query this table serves.
 */
class Migration1755720000CreateAssistantTables extends MigrationStep
{
    public function getCreationTimestamp(): int
    {
        return 1755720000;
    }

    /**
     * @throws \Doctrine\DBAL\Exception propagated deliberately. A migration that cannot create its
     *         tables must fail loudly: Shopware reports the failure and leaves the plugin
     *         un-updated, whereas swallowing it would leave a plugin that boots and then errors on
     *         the first shopper message.
     */
    public function update(Connection $connection): void
    {
        $connection->executeStatement(<<<'SQL'
                CREATE TABLE IF NOT EXISTS `swag_assistant_conversation` (
                    `id`                BINARY(16)   NOT NULL,
                    `sales_channel_id`  VARCHAR(32)  NOT NULL,
                    `locale`            VARCHAR(32)  NULL,
                    `turn_count`        INT(11)      NOT NULL DEFAULT 0,
                    `outcome`           VARCHAR(64)  NULL,
                    `total_ms`          INT(11)      NOT NULL DEFAULT 0,
                    `transcript`        JSON         NULL,
                    `created_at`        DATETIME(3)  NOT NULL,
                    `updated_at`        DATETIME(3)  NULL,
                    PRIMARY KEY (`id`),
                    KEY `idx.swag_assistant_conversation.sales_channel` (`sales_channel_id`),
                    KEY `idx.swag_assistant_conversation.created_at` (`created_at`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
            SQL);

        $connection->executeStatement(<<<'SQL'
                CREATE TABLE IF NOT EXISTS `swag_assistant_trace_event` (
                    `id`               BINARY(16)   NOT NULL,
                    `conversation_id`  BINARY(16)   NOT NULL,
                    `seq`              INT(11)      NOT NULL DEFAULT 0,
                    `stage`            VARCHAR(64)  NOT NULL,
                    `payload`          JSON         NULL,
                    `created_at`       DATETIME(3)  NOT NULL,
                    -- A trace event is written once and never updated, so this stays NULL forever.
                    -- It exists because EntityDefinition::defaultFields() appends an UpdatedAtField
                    -- to EVERY definition whether declared or not, and `dal:validate` fails without
                    -- the column. Found by running that command rather than by reasoning.
                    `updated_at`       DATETIME(3)  NULL,
                    PRIMARY KEY (`id`),
                    KEY `idx.swag_assistant_trace_event.conversation_seq` (`conversation_id`, `seq`),
                    CONSTRAINT `fk.swag_assistant_trace_event.conversation_id`
                        FOREIGN KEY (`conversation_id`)
                        REFERENCES `swag_assistant_conversation` (`id`)
                        ON DELETE CASCADE ON UPDATE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
            SQL);
    }

    public function updateDestructive(Connection $connection): void
    {
        // Nothing destructive. Dropping these tables would destroy the merchant's trace history,
        // which is theirs rather than ours, so removal is a deliberate uninstall decision and not a
        // migration side effect.
    }
}
